### ISSUE TITLE
PDF and some pages need to remove from sitemap

### ISSUE THREAD

**Issue by RajMankotia** [hlxsites/moleculardevices#1188]
I have added the file on https://app.slack.com/, but some more. Please remove all these from the sitemap.
[Gated-pdfs.txt](https://github.com/hlxsites/moleculardevices/files/12595630/Gated-pdfs.txt)

**Comment by RajMankotia** [comment]
these are still pending-
https://www.moleculardevices.com/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-softmax-pro-software
https://www.moleculardevices.com/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-microplate-readers

and 7 pages of https://www.moleculardevices.com/resources/data/

**Comment by mhaack** [comment]
@RajMankotia  please advice on the `/en/assets/white-paper/` and `/resources/data/`should they all excluded?

**Comment by RajMankotia** [comment]
https://www.moleculardevices.com/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-softmax-pro-software
https://www.moleculardevices.com/en/assets/white-paper/br/gxp-regulated-industry-assessments-of-microplate-readers
for these Landing Page has been removed and now we have PDFs for these two. So these show errors in the sitemap. 
and /resources/data/ also be not part of sitemap

**Comment by mhaack** [comment]
Fixed

**Comment by RajMankotia** [comment]
still showing-
<img width="960" alt="image" src="https://github.com/hlxsites/moleculardevices/assets/142977173/412993f2-ba21-4552-8661-543a974cd3ed">
and https://www.moleculardevices.com/resources/data/cgmp-standard-curve

**Comment by mhaack** [comment]
Fixed now manually, however the two white papers are user error. Lets take that on Slack.
